version: '3.8'
networks:
  backend:
  frontend:
  proxy:
services:
  backend:
    container_name: backend_hdb
    image: historydb:2.0
    environment:
      - MONGODB_BASE=historydev
    networks:
      - backend
  proxy:
    container_name: proxy_hdb
    image: nginx:1.19.2-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - proxy
      - backend
    ports:
      - 8080:80
    depends_on:
      - backend
  frontend:
    container_name: frontend_hdb
    image: nginx:1.19.2-alpine
    volumes:
      - ./web/build/hdb:/usr/share/nginx/html/
    ports:
      - 80:80
    depends_on:
      - backend
      - proxy
    networks:
      - frontend
