name: Build App for Development

on:
  push:
    branches:
      - 2.1.0-devel
  pull_request:
    branches:
      - 2.1.0-devel

jobs:
  test:
    name: Testing backend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Install dependencies
      run: cd server && npm install

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: 4.0

    - name: Test
      run: |
        node --version
        npm --version
        cd server && npm run coverage

  build-deploy-backend:
    name: Build Deploy Backend 2.1.0-devel
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: glopes/historydb
        dockerfile: server/Dockerfile
        tags: 2.1.0-devel
